# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php,Service/EventExporter}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\Tests\Fixtures\:
        resource: '../tests/Fixtures'
        tags: ['doctrine.fixture.orm']

    # Registers as services EventExporter component classes

    # @todo Uncomment this and move to bundle config in step 4
#    bravik\CalendarBundle\Service\EventExporter\:
#        resource: '../src/Service/EventExporter/*'
#
#    # Register EventProvider as a service and explicitly pass 2 exporters to it's constructor
#    bravik\CalendarBundle\Service\EventExporter\ExporterManager:
#        arguments:
#            $exporters:
#                - '@bravik\CalendarBundle\Service\EventExporter\Exporters\GoogleCalendarExporter'
#                - '@bravik\CalendarBundle\Service\EventExporter\Exporters\ICalendarExporter'

